### ISSUE TITLE
trash

### ISSUE THREAD

**Issue by Dev-Shaz** [MailarYT/MailarShaz_Drugs#1]
hi

**Comment by MailarYT** [comment]
credited u son

**Comment by Dev-Shaz** [comment]
Still doesnt mean you can release it

**Comment by MailarYT** [comment]
u made 1 drug and diamond and animations and system
i made 7 drugs and blips coords more u drugs was in the highway 

U have added me to github so i own it too
![image](https://user-images.githubusercontent.com/83369389/120631031-14d7cb80-c470-11eb-95c2-47f1c112aa0e.png)
